/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IngredientesRouteImport } from './routes/ingredientes'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as ConfiancaRouteImport } from './routes/confianca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrinksIndexRouteImport } from './routes/drinks.index'
import { Route as DrinksIdRouteImport } from './routes/drinks.$id'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as DrinksIdIndexRouteImport } from './routes/drinks.$id.index'
import { Route as AuthenticatedDrinksNovoRouteImport } from './routes/_authenticated/drinks.novo'
import { Route as AuthenticatedDrinksIdEditarRouteImport } from './routes/_authenticated/drinks.$id.editar'

const IngredientesRoute = IngredientesRouteImport.update({
  id: '/ingredientes',
  path: '/ingredientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiancaRoute = ConfiancaRouteImport.update({
  id: '/confianca',
  path: '/confianca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksIndexRoute = DrinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrinksRoute,
} as any)
const DrinksIdRoute = DrinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DrinksRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DrinksIdIndexRoute = DrinksIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrinksIdRoute,
} as any)
const AuthenticatedDrinksNovoRoute = AuthenticatedDrinksNovoRouteImport.update({
  id: '/drinks/novo',
  path: '/drinks/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrinksIdEditarRoute =
  AuthenticatedDrinksIdEditarRouteImport.update({
    id: '/drinks/$id/editar',
    path: '/drinks/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/drinks': typeof DrinksRouteWithChildren
  '/ingredientes': typeof IngredientesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/drinks/$id': typeof DrinksIdRouteWithChildren
  '/drinks/': typeof DrinksIndexRoute
  '/drinks/novo': typeof AuthenticatedDrinksNovoRoute
  '/drinks/$id/': typeof DrinksIdIndexRoute
  '/drinks/$id/editar': typeof AuthenticatedDrinksIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/ingredientes': typeof IngredientesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/drinks': typeof DrinksIndexRoute
  '/drinks/novo': typeof AuthenticatedDrinksNovoRoute
  '/drinks/$id': typeof DrinksIdIndexRoute
  '/drinks/$id/editar': typeof AuthenticatedDrinksIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confianca': typeof ConfiancaRoute
  '/drinks': typeof DrinksRouteWithChildren
  '/ingredientes': typeof IngredientesRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/drinks/$id': typeof DrinksIdRouteWithChildren
  '/drinks/': typeof DrinksIndexRoute
  '/_authenticated/drinks/novo': typeof AuthenticatedDrinksNovoRoute
  '/drinks/$id/': typeof DrinksIdIndexRoute
  '/_authenticated/drinks/$id/editar': typeof AuthenticatedDrinksIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confianca'
    | '/drinks'
    | '/ingredientes'
    | '/importar'
    | '/usuarios'
    | '/drinks/$id'
    | '/drinks/'
    | '/drinks/novo'
    | '/drinks/$id/'
    | '/drinks/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confianca'
    | '/ingredientes'
    | '/importar'
    | '/usuarios'
    | '/drinks'
    | '/drinks/novo'
    | '/drinks/$id'
    | '/drinks/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confianca'
    | '/drinks'
    | '/ingredientes'
    | '/_authenticated/importar'
    | '/_authenticated/usuarios'
    | '/drinks/$id'
    | '/drinks/'
    | '/_authenticated/drinks/novo'
    | '/drinks/$id/'
    | '/_authenticated/drinks/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiancaRoute: typeof ConfiancaRoute
  DrinksRoute: typeof DrinksRouteWithChildren
  IngredientesRoute: typeof IngredientesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ingredientes': {
      id: '/ingredientes'
      path: '/ingredientes'
      fullPath: '/ingredientes'
      preLoaderRoute: typeof IngredientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confianca': {
      id: '/confianca'
      path: '/confianca'
      fullPath: '/confianca'
      preLoaderRoute: typeof ConfiancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks/': {
      id: '/drinks/'
      path: '/'
      fullPath: '/drinks/'
      preLoaderRoute: typeof DrinksIndexRouteImport
      parentRoute: typeof DrinksRoute
    }
    '/drinks/$id': {
      id: '/drinks/$id'
      path: '/$id'
      fullPath: '/drinks/$id'
      preLoaderRoute: typeof DrinksIdRouteImport
      parentRoute: typeof DrinksRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/drinks/$id/': {
      id: '/drinks/$id/'
      path: '/'
      fullPath: '/drinks/$id/'
      preLoaderRoute: typeof DrinksIdIndexRouteImport
      parentRoute: typeof DrinksIdRoute
    }
    '/_authenticated/drinks/novo': {
      id: '/_authenticated/drinks/novo'
      path: '/drinks/novo'
      fullPath: '/drinks/novo'
      preLoaderRoute: typeof AuthenticatedDrinksNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drinks/$id/editar': {
      id: '/_authenticated/drinks/$id/editar'
      path: '/drinks/$id/editar'
      fullPath: '/drinks/$id/editar'
      preLoaderRoute: typeof AuthenticatedDrinksIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedDrinksNovoRoute: typeof AuthenticatedDrinksNovoRoute
  AuthenticatedDrinksIdEditarRoute: typeof AuthenticatedDrinksIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedDrinksNovoRoute: AuthenticatedDrinksNovoRoute,
  AuthenticatedDrinksIdEditarRoute: AuthenticatedDrinksIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DrinksIdRouteChildren {
  DrinksIdIndexRoute: typeof DrinksIdIndexRoute
}

const DrinksIdRouteChildren: DrinksIdRouteChildren = {
  DrinksIdIndexRoute: DrinksIdIndexRoute,
}

const DrinksIdRouteWithChildren = DrinksIdRoute._addFileChildren(
  DrinksIdRouteChildren,
)

interface DrinksRouteChildren {
  DrinksIdRoute: typeof DrinksIdRouteWithChildren
  DrinksIndexRoute: typeof DrinksIndexRoute
}

const DrinksRouteChildren: DrinksRouteChildren = {
  DrinksIdRoute: DrinksIdRouteWithChildren,
  DrinksIndexRoute: DrinksIndexRoute,
}

const DrinksRouteWithChildren =
  DrinksRoute._addFileChildren(DrinksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiancaRoute: ConfiancaRoute,
  DrinksRoute: DrinksRouteWithChildren,
  IngredientesRoute: IngredientesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
